"""The standard library's recipes as Python functions — generated, do not edit.

Generated by ``tools/gen_std.py`` from ``_recipes.json`` (``datars describe --json``): one function
per ``@datars/std`` recipe, with its parameters, defaults and theme tokens. Each returns a
:class:`~datars.Node` — a ``use`` node of the document IR, the same JSON the TypeScript SDK
writes — which the engine expands. Parameters are keyword-only and snake_case (``x_type`` is
the recipe's ``xType``); ``None`` means "the recipe's default". Table parameters take a table
name, a DataFrame or :func:`datars.data`; prop parameters take a value or :func:`datars.e`.

    import datars as dr
    node = dr.std.pie(data=df, category="party", value="share", inner=0.6)
    dr.chart(node)          # a displayable Chart

Node options (``key``, ``when``, ``size``, …) go through :meth:`Node.opts`.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from ._node import Node, use

#: Every recipe's description by short name, as ``datars describe --json`` prints it.
RECIPES: dict[str, dict] = {
    rid.rsplit("/", 1)[-1]: spec
    for rid, spec in json.loads((Path(__file__).parent / "_recipes.json").read_text(encoding="utf-8")).items()
}

#: Python parameter name → recipe parameter name, per recipe (where they differ).
RENAMES: dict[str, dict[str, str]] = {}


def annotate(
    *,
    x: Any = None,
    y: Any = None,
    connector: Any = None,
    dot: Any = None,
    dx: Any = None,
    dy: Any = None,
    head: Any = None,
    ink: Any = None,
    pin: Any = None,
    text: Any = None,
    width: Any = None,
) -> Node:
    """A callout: text offset from a point (in plot coordinates via scales, or px), with a
    connector and a dot.

    Recipe ``@datars/std/annotate``.

    Parameters
    ----------
    connector : "line" | "elbow" | "curve" | "none", default "line"
    dot : bool, default True
    dx : float, default 40
    dy : float, default -36
    head : bool, default False
        An arrowhead at the point.
    ink : str, default "$ink"
    pin : bool, default False
        Pinned at the point: dot, connector and text keep screen size under cameras (map
        callouts).
    text : str, default ""
    width : float, default 160
    x : value | Expr
        x position (expression, e.g. scale.x('SD'))
    y : value | Expr

    Theme tokens: ``ink``, ``paper``, ``size.label``.
    """
    return use('@datars/std/annotate', locals(), RENAMES['annotate'])


RENAMES['annotate'] = {}


def area(
    *,
    data: Any = None,
    x: Any = None,
    y: Any = None,
    clip: Any = None,
    color: Any = None,
    curve: Any = None,
    fill: Any = None,
    opacity: Any = None,
    series: Any = None,
    x_type: Any = None,
    y0: Any = None,
) -> Node:
    """Filled areas from a baseline (0, or `y0`) to y — one per series. For stacked areas, give a
    stacked table (op.stack) and y0/y fields.

    Recipe ``@datars/std/area``.

    Parameters
    ----------
    clip : bool, default False
        Clip to the plot area.
    color : str
    curve : str, default "monotone-x"
    data : str | DataFrame | Data
    fill : value | Expr
    opacity : float, default 0.85
    series : str
    x : str
    x_type : str, default "linear"
        (``xType``)
    y : str
    y0 : str
        Lower bound field (default: zero).

    Theme tokens: ``mark``.
    """
    return use('@datars/std/area', locals(), RENAMES['area'])


RENAMES['area'] = {"x_type": "xType"}


def attribution(
    *,
    ink: Any = None,
    link: Any = None,
    text: Any = None,
) -> Node:
    """The data credit a map owes (OpenStreetMap's licence requires it), in the bottom-right corner
    of its box, legible and linked to the licence page (hosts make it a real link; SVG/PDF keep
    it). Place it outside the map's view so it stays put while the camera moves.

    Recipe ``@datars/std/attribution``.

    Parameters
    ----------
    ink : str, default "$map.label"
    link : str, default "https://www.openstreetmap.org/copyright"
        Where the credit links (OpenStreetMap's copyright page, as its guidelines ask).
    text : str, default "© OpenStreetMap contributors, Natural Earth"

    Theme tokens: ``map.label``, ``map.label-halo``.
    """
    return use('@datars/std/attribution', locals(), RENAMES['attribution'])


RENAMES['attribution'] = {}


def axis(
    *,
    data: Any = None,
    field: Any = None,
    format: Any = None,
    label: Any = None,
    line: Any = None,
    orient: Any = None,
    prefix: Any = None,
    scale: Any = None,
    suffix: Any = None,
    ticks: Any = None,
    type: Any = None,
) -> Node:
    """An axis for a scale: tick labels, tick marks and a domain line. Labels never pile up: a
    horizontal numeric axis asks for as many ticks as its measured labels fit; category names
    wrap in their band, turn 45° when a word is wider than the band, and leave out every k-th
    name only when even that doesn't fit.

    Recipe ``@datars/std/axis``.

    Parameters
    ----------
    data : str | DataFrame | Data
        The table a band scale's categories come from (with `field`): their names are measured,
        so a horizontal axis wraps, turns or leaves out labels only as they need.
    field : str
        The categories' field in `data`.
    format : str
        Number format for labels (d3-format).
    label : str
        Axis title.
    line : bool, default True
        Draw the domain line.
    orient : "left" | "bottom" | "right" | "top", default "left"
    prefix : str
        Before each number label ('$').
    scale : str, default "y"
        The scale to draw.
    suffix : str
        After it ('M', ' kr').
    ticks : float, default 0
        Tick count hint (0 = automatic: from the axis length, and across, from how many of its
        measured labels fit).
    type : str
        The scale's type (`linear`, `log`, `time`, …; the plot passes it). A horizontal numeric
        axis fits its tick count to its labels' measured width.

    Theme tokens: ``muted``, ``rule``, ``size.label``.
    """
    return use('@datars/std/axis', locals(), RENAMES['axis'])


RENAMES['axis'] = {}


def bar(
    *,
    data: Any = None,
    x: Any = None,
    y: Any = None,
    chapter: Any = None,
    color: Any = None,
    fill: Any = None,
    format: Any = None,
    label: Any = None,
    labels: Any = None,
    prefix: Any = None,
    radius: Any = None,
    selected: Any = None,
    suffix: Any = None,
    x_type: Any = None,
    y_type: Any = None,
) -> Node:
    """Bars from a category field on a band scale to a value on a linear scale (vertical or
    horizontal, decided by which axis is the band). Negative values hang below zero.

    Recipe ``@datars/std/bar``.

    Parameters
    ----------
    chapter : str
        Clicking a bar enters this program chapter with the bar's category (drill-down).
    color : str
    data : str | DataFrame | Data
    fill : value | Expr
        Fill ink or expression (default: the colour scale, else $mark).
    format : str, default ",.1~f"
        Label number format.
    label : value | Expr
        Bar label (tooltip, accessible name): an expression over the row; default `name: value`.
    labels : bool, default False
        Value labels on the bars (they count when values change).
    prefix : str
        Before each value label's number ('$').
    radius : float, default 0
        Corner radius (0: the theme's `radius.bar`).
    selected : str
        A keyset signal: selected bars stay strong, others recede.
    suffix : str
        After it ('M', ' kr').
    x : str
    x_type : str, default "band"
        (``xType``)
    y : str
    y_type : str, default "linear"
        (``yType``)

    Theme tokens: ``mark``, ``ink``, ``muted``, ``dim``, ``size.label``, ``radius.bar``.
    """
    return use('@datars/std/bar', locals(), RENAMES['bar'])


RENAMES['bar'] = {"x_type": "xType", "y_type": "yType"}


def basemap(
    *,
    boundaries: Any = None,
    buildings: Any = None,
    labels: Any = None,
    layers: Any = None,
    part: Any = None,
    roads: Any = None,
    sea: Any = None,
    source: Any = None,
    tile_size: Any = None,
) -> Node:
    """A basemap from a vector-tile source (our own OSM / Natural Earth archives): sea, land,
    water, parks, buildings, roads by class, borders and place labels, in the enclosing map's
    projection, styled by the theme's map tokens. Put it first inside a view with a `geo`
    coordinate system; data layers go after it (or between `part: base` and `part: labels`).

    Recipe ``@datars/std/basemap``.

    Parameters
    ----------
    boundaries : bool, default True
        Country borders.
    buildings : bool, default True
    labels : bool, default True
        Place names (screen-space placement, no overlaps).
    layers : object
        Archive layer names, if they differ from the defaults: { land, water, lakes, parks,
        rivers, buildings, roads, boundaries, places }.
    part : "all" | "base" | "labels", default "all"
        Split the map around data layers: `base` below them, `labels` above.
    roads : bool, default True
    sea : bool, default True
        Fill the world behind the land with $map.water.
    source : str | DataFrame | Data
        A `tiles` source (data.tiles(url)).
    tile_size : float, default 512
        On-screen tile size the zoom aims for (px). Smaller: more detail, more tiles.
        (``tileSize``)

    Theme tokens: ``map.water``, ``map.land``, ``map.park``, ``map.building``, ``map.road``, ``map.road-major``, ``map.border``, ``map.label``, ``map.label-halo``.
    """
    return use('@datars/std/basemap', locals(), RENAMES['basemap'])


RENAMES['basemap'] = {"tile_size": "tileSize"}


def bollinger(
    *,
    data: Any = None,
    x: Any = None,
    y: Any = None,
    fill: Any = None,
    full: Any = None,
    k: Any = None,
    label: Any = None,
    middle: Any = None,
    opacity: Any = None,
    series: Any = None,
    source: Any = None,
    stroke: Any = None,
    width: Any = None,
    window: Any = None,
    x_type: Any = None,
) -> Node:
    """Bollinger bands: the moving average of `y` over `window` rows with a shaded band `k`
    standard deviations (population σ) above and below it — where the price is stretched, and
    how volatile it is. Computes over `source` when given, like `movingAverage`; the plot fits
    its value axis to the band.

    Recipe ``@datars/std/bollinger``.

    Parameters
    ----------
    data : str | DataFrame | Data
        The rows to draw (default: the plot's).
    fill : str, default "$accent"
        Band ink.
    full : bool, default True
        Only full windows.
    k : float, default 2
        Band half-width in standard deviations.
    label : str
        Name in the indicator key (default `BB 20, 2`).
    middle : bool, default True
        Draw the middle (moving average) line.
    opacity : float, default 0.1
        Band opacity.
    series : str
        One band per series.
    source : str | DataFrame | Data
        A longer history to compute over (see movingAverage).
    stroke : str, default "$accent"
        Ink of the band's edges and middle line.
    width : float, default 1
        Edge stroke width.
    window : float, default 20
        Rows per window.
    x : str
        The date field.
    x_type : str, default "band"
        `band`: trading days side by side, no weekend gaps (the plot's); `time`/`linear`: rows
        by value. (``xType``)
    y : str
        The field (default: the plot's `y`).

    Theme tokens: ``accent``.
    """
    return use('@datars/std/bollinger', locals(), RENAMES['bollinger'])


RENAMES['bollinger'] = {"x_type": "xType"}


def calendar(
    *,
    data: Any = None,
    cell: Any = None,
    date: Any = None,
    label: Any = None,
    value: Any = None,
) -> Node:
    """A calendar heatmap: a week-column × weekday-row grid per year, coloured by value.

    Recipe ``@datars/std/calendar``.

    Parameters
    ----------
    cell : float, default 0
        Cell size in px (0 = fit the width).
    data : str | DataFrame | Data
    date : str
        A date (or day-of-year with a year field).
    label : value | Expr
        Day label (tooltip, accessible name); default `date: value`.
    value : str
    """
    return use('@datars/std/calendar', locals(), RENAMES['calendar'])


RENAMES['calendar'] = {}


def candlestick(
    *,
    data: Any = None,
    x: Any = None,
    y: Any = None,
    close: Any = None,
    down: Any = None,
    format: Any = None,
    high: Any = None,
    hollow: Any = None,
    label: Any = None,
    low: Any = None,
    open: Any = None,
    up: Any = None,
    width: Any = None,
    x_type: Any = None,
) -> Node:
    """Candlesticks: per row a wick from low to high and a body from open to close, in `$up` when
    the close is at or above the open and `$down` below. Use in a plot with `xType: "band"` over
    dates for trading days without gaps; the plot fits its value axis to the lows and highs.
    Hovering a candle reads its date, OHLC and change.

    Recipe ``@datars/std/candlestick``.

    Parameters
    ----------
    close : str
        Closing price field (default: the plot's `y`, else `close`).
    data : str | DataFrame | Data
        The rows to draw (default: the plot's).
    down : str, default "$down"
        Ink of falling candles.
    format : str, default ",.2f"
        Price format in labels.
    high : str, default "high"
        High field.
    hollow : bool, default False
        Hollow candles: rising bodies outlined, falling ones filled.
    label : value | Expr
        Candle label (tooltip, accessible name); default date · O H L C (change).
    low : str, default "low"
        Low field.
    open : str, default "open"
        Opening price field.
    up : str, default "$up"
        Ink of rising candles.
    width : float, default 0
        Body width: a fraction of the band on a band scale (0 = the band, whose padding leaves
        the gaps), px on a continuous scale (0 = 70% of the spacing).
    x : str
        The date (or time) field.
    x_type : str, default "band"
        `band`: trading days side by side, no weekend gaps (the plot's); `time`/`linear`: rows
        by value. (``xType``)
    y : str
        The plot's value field: the close, unless `close` is given.

    Theme tokens: ``up``, ``down``, ``paper``.
    """
    return use('@datars/std/candlestick', locals(), RENAMES['candlestick'])


RENAMES['candlestick'] = {"x_type": "xType"}


def card(
    *,
    at: Any = None,
    dodge: Any = None,
    kicker: Any = None,
    margin: Any = None,
    text: Any = None,
    title: Any = None,
    width: Any = None,
) -> Node:
    """A text card over the chart: an optional kicker and title over wrapped body text, on the
    theme's card surface, anchored to a corner or edge of its box. Drawn by the engine (so it's
    in video, PNG and PDF too); empty text hides it, and a card whose text changes between
    states morphs.

    Recipe ``@datars/std/card``.

    Parameters
    ----------
    at : "auto" | "top-left" | "top" | "top-right" | "left" | "center" | "right" | "bottom-left" | "bottom" | "bottom-right", default "auto"
        Where the card sits in its box — or an expression over signals, for a card that moves
        between states. With `dodge`, `auto` (and any anchor, as a first choice) moves it to
        where it covers the least data and text.
    dodge : bool, default True
        Move out of the way of data and text (taking a band below the chart when nowhere is
        free). Off: the card stays at `at` (`auto`: top-right), over whatever is there — a card
        over a map, where land covers everything.
    kicker : value | Expr
        A small accent line above the title (empty: no line).
    margin : float, default 12
        Space between the card and its box's edges (px, or [top, right, bottom, left]).
    text : value | Expr
        The body text (a string, or an expression over signals: one card narrating every state).
    title : value | Expr
        A bold line above the text (empty: no line).
    width : float, default 260
        Card width (px); text wraps inside.

    Theme tokens: ``card``, ``card-ink``, ``card-ink-2``, ``card-line``, ``radius.card``, ``accent``, ``size.body``, ``size.small``.
    """
    return use('@datars/std/card', locals(), RENAMES['card'])


RENAMES['card'] = {}


def cell(
    *,
    data: Any = None,
    x: Any = None,
    y: Any = None,
    color: Any = None,
    format: Any = None,
    gap: Any = None,
    label: Any = None,
) -> Node:
    """Heatmap cells: a rectangle per (x, y) on two band scales, coloured by the colour scale. Keys
    (x, y) match grouped bars, so the two morph.

    Recipe ``@datars/std/cell``.

    Parameters
    ----------
    color : str
        The value field (on a sequential/diverging colour scale).
    data : str | DataFrame | Data
    format : str, default ".1~f"
    gap : float, default 1
    label : value | Expr
        Cell label (tooltip, accessible name); default `y, x: value`.
    x : str
    y : str
    """
    return use('@datars/std/cell', locals(), RENAMES['cell'])


RENAMES['cell'] = {}


def cloud(
    *,
    data: Any = None,
    x: Any = None,
    y: Any = None,
    bbox: Any = None,
    budget: Any = None,
    children: Any = None,
    explore: Any = None,
    fill: Any = None,
    glow: Any = None,
    glow_opacity: Any = None,
    glow_points: Any = None,
    label: Any = None,
    max_zoom: Any = None,
    name: Any = None,
    opacity: Any = None,
    padding: Any = None,
    points: Any = None,
    r: Any = None,
) -> Node:
    """A point cloud of any size (millions of rows): dots at their own x/y in an explorable view —
    a density-preserving sample at every zoom, every row up close, a tooltip on each.

    Recipe ``@datars/std/cloud``.

    Parameters
    ----------
    bbox : object
        The extent to frame, [x0, y0, x1, y1] in the rows' units. Default: the rows' extent —
        give it for millions of rows (finding it reads them all) and for point archives.
    budget : float, default 2048
        Rows per tile of the index at average density (smaller: lighter tiles, more of them).
    children : list[Node]
        Drawn over the dots, in the same coordinates (annotations, marks).
    data : str | DataFrame | Data
        A table, or a point archive (a `tiles` source the publish compiler wrote).
    explore : str, default "cloud"
        The signals the camera explores with (`<explore>.x`, `.y`, `.zoom`).
    fill : value | Expr
        Dot ink, or an expression over the row (default $mark).
    glow : value | Expr
        Radius (px) of a glow under the dots (a number or an expression over the row): a sample
        drawn large and faint, so density reads at a glance and, up close, stars bloom. None by
        default.
    glow_opacity : value | Expr
        The glow's opacity per dot: a number (default 0.05) or an expression over the row
        (weight bright rows). (``glowOpacity``)
    glow_points : float, default 6000
        How many dots the glow draws at most. (``glowPoints``)
    label : value | Expr
        Tooltip and accessible name per row (default `x, y`).
    max_zoom : float, default 2048
        How far in the reader can zoom, × the whole. (``maxZoom``)
    name : str
        What the rows are, for the accessible description ('4,000,000 stars').
    opacity : value | Expr
        Per-dot opacity: an expression over the row.
    padding : float, default 12
    points : float, default 150000
        The most dots a frame draws: a view holding more shows a uniform sample this size, one
        holding fewer shows every row.
    r : value | Expr
        Dot radius in screen px: a number, or an expression over the row.
    x : str
    y : str

    Theme tokens: ``mark``.
    """
    return use('@datars/std/cloud', locals(), RENAMES['cloud'])


RENAMES['cloud'] = {"glow_opacity": "glowOpacity", "glow_points": "glowPoints", "max_zoom": "maxZoom"}


def dot(
    *,
    data: Any = None,
    x: Any = None,
    y: Any = None,
    color: Any = None,
    fill: Any = None,
    r: Any = None,
    x_type: Any = None,
    y_type: Any = None,
) -> Node:
    """A dot per category at its value (a dot plot).

    Recipe ``@datars/std/dot``.

    Parameters
    ----------
    color : str
    data : str | DataFrame | Data
    fill : value | Expr
    r : float, default 6
    x : str
    x_type : str, default "band"
        (``xType``)
    y : str
    y_type : str, default "linear"
        (``yType``)
    """
    return use('@datars/std/dot', locals(), RENAMES['dot'])


RENAMES['dot'] = {"x_type": "xType", "y_type": "yType"}


def dot_density(
    *,
    data: Any = None,
    fill: Any = None,
    key: Any = None,
    per: Any = None,
    r: Any = None,
    seed: Any = None,
    source: Any = None,
    value: Any = None,
) -> Node:
    """Dot density: one dot per `per` units of a region's value, scattered evenly inside it
    (seeded, deterministic).

    Recipe ``@datars/std/dotDensity``.

    Parameters
    ----------
    data : str | DataFrame | Data
    fill : value | Expr
    key : str
    per : float, default 1000
    r : float, default 1.2
    seed : float, default 1
    source : str | DataFrame | Data
    value : str
    """
    return use('@datars/std/dotDensity', locals(), RENAMES['dotDensity'])


RENAMES['dotDensity'] = {}


def drawdown(
    *,
    data: Any = None,
    x: Any = None,
    y: Any = None,
    area: Any = None,
    color: Any = None,
    fill: Any = None,
    format: Any = None,
    labels: Any = None,
    opacity: Any = None,
    series: Any = None,
    source: Any = None,
    stroke: Any = None,
    width: Any = None,
    x_type: Any = None,
) -> Node:
    """Drawdown: how far each series sits below its running peak (0 at a new high, −25 % a quarter
    below it), as an area hanging from zero — the pain chart next to a performance chart. With
    `source`, peaks count from the start of the whole history instead of the first visible row.
    Use with `format: ".0%"` on the plot.

    Recipe ``@datars/std/drawdown``.

    Parameters
    ----------
    area : bool, default True
        Shade from zero (one series; several draw lines only).
    color : str
        The plot's colour field (line and label inks).
    data : str | DataFrame | Data
        The rows to draw (default: the plot's).
    fill : str, default "$down"
        Area ink (one series).
    format : str, default "+.1%"
        Format of the drawdown in end labels.
    labels : bool, default True
        Label each series' end with its name and current drawdown (with a series; pushed apart).
    opacity : float, default 0.22
        Area opacity.
    series : str
        One drawdown per series (default: the colour field).
    source : str | DataFrame | Data
        A longer history: peaks before the rows on show count too.
    stroke : value | Expr
        Line ink (default: $down, or the colour scale per series).
    width : float, default 1.5
        Stroke width.
    x : str
        The date field.
    x_type : str, default "band"
        `band`: trading days side by side, no weekend gaps (the plot's); `time`/`linear`: rows
        by value. (``xType``)
    y : str
        The price field (default: the plot's `y`).

    Theme tokens: ``down``, ``size.label``.
    """
    return use('@datars/std/drawdown', locals(), RENAMES['drawdown'])


RENAMES['drawdown'] = {"x_type": "xType"}


def facet(
    *,
    data: Any = None,
    by: Any = None,
    chart: Any = None,
    columns: Any = None,
    gap: Any = None,
    shared: Any = None,
) -> Node:
    """Small multiples: the given chart once per value of `by`, in a grid; inside, the chart's
    `data` is that group's rows ("@group"), on scales shared across panels unless `shared:
    false`.

    Recipe ``@datars/std/facet``.

    Parameters
    ----------
    by : str
    chart : object
        A chart (e.g. plot(...)) to repeat; its data is replaced by each group.
    columns : float, default 3
    data : str | DataFrame | Data
    gap : float, default 16
    shared : bool, default True
        Every panel on the same x and y scales (the whole table's extent), so panels compare at
        a glance; off: each fits its own rows.
    """
    return use('@datars/std/facet', locals(), RENAMES['facet'])


RENAMES['facet'] = {}


def funnel(
    *,
    data: Any = None,
    conversion: Any = None,
    fill: Any = None,
    format: Any = None,
    stage: Any = None,
    title: Any = None,
    value: Any = None,
) -> Node:
    """A funnel: stage names in a measured column, centred bars in stage order joined by tapering
    connectors, each labelled with the conversion from the stage before.

    Recipe ``@datars/std/funnel``.

    Parameters
    ----------
    conversion : bool, default True
        Connectors between stages, labelled with the share that carries on (↓ 44 %).
    data : str | DataFrame | Data
    fill : value | Expr
        The bars' colour (default $mark); labels inside take whichever of ink and paper reads on
        it.
    format : str, default ",.0f"
    stage : str
    title : str
        A title above the funnel.
    value : str

    Theme tokens: ``mark``, ``ink``, ``ink-2``, ``muted``, ``paper``, ``size.label``, ``font.title``, ``size.title``.
    """
    return use('@datars/std/funnel', locals(), RENAMES['funnel'])


RENAMES['funnel'] = {}


def geo_lines(
    *,
    data: Any = None,
    dash: Any = None,
    format: Any = None,
    ink: Any = None,
    key: Any = None,
    source: Any = None,
    stops: Any = None,
    value: Any = None,
    width: Any = None,
) -> Node:
    """Line features of a geo source (roads, borders, courses, routes) as non-scaling strokes. With
    `data` and `key`, one line per row (the feature with that id) — data, not decoration —
    coloured by `value` on piecewise `stops`.

    Recipe ``@datars/std/geoLines``.

    Parameters
    ----------
    dash : bool, default False
    data : str | DataFrame | Data
    format : str, default ",.1~f"
    ink : str, default "$map.border"
    key : str
        The data field holding each row's feature id.
    source : str | DataFrame | Data
    stops : str
        Piecewise colour stops for `value` (`#a 0 · #b 10`).
    value : str
        Colour lines by this field (with `stops`).
    width : float, default 1
    """
    return use('@datars/std/geoLines', locals(), RENAMES['geoLines'])


RENAMES['geoLines'] = {}


def geo_points(
    *,
    data: Any = None,
    fill: Any = None,
    key: Any = None,
    label: Any = None,
    lat: Any = None,
    lon: Any = None,
    r: Any = None,
) -> Node:
    """Points at lon/lat (cities, events, stations), in the enclosing map's projection, in
    $map.marker ringed by $map.label-halo so they read on any land.

    Recipe ``@datars/std/geoPoints``.

    Parameters
    ----------
    data : str | DataFrame | Data
    fill : value | Expr
    key : str
    label : value | Expr
    lat : str
    lon : str
    r : value | Expr

    Theme tokens: ``map.marker``, ``map.label-halo``.
    """
    return use('@datars/std/geoPoints', locals(), RENAMES['geoPoints'])


RENAMES['geoPoints'] = {}


def grid(
    *,
    count: Any = None,
    orient: Any = None,
    scale: Any = None,
    ticks: Any = None,
) -> Node:
    """Gridlines at a scale's ticks across the plot area.

    Recipe ``@datars/std/grid``.

    Parameters
    ----------
    count : value | Expr
        A tick count as an expression — the axis's own (a plot passes it), so every gridline
        meets a tick.
    orient : "horizontal" | "vertical", default "horizontal"
    scale : str, default "y"
    ticks : float, default 0

    Theme tokens: ``grid``, ``stroke.grid``.
    """
    return use('@datars/std/grid', locals(), RENAMES['grid'])


RENAMES['grid'] = {}


def grouped(
    *,
    data: Any = None,
    x: Any = None,
    y: Any = None,
    color: Any = None,
    format: Any = None,
    gap: Any = None,
    labels: Any = None,
    prefix: Any = None,
    series: Any = None,
    suffix: Any = None,
    x_type: Any = None,
    y_type: Any = None,
) -> Node:
    """Grouped (dodged) bars: a group per x, a bar per series side by side. Keys (series, x),
    shared with stacked segments and heatmap cells, so the three morph.

    Recipe ``@datars/std/grouped``.

    Parameters
    ----------
    color : str
    data : str | DataFrame | Data
    format : str, default ",.1~f"
        Number format of each bar's label.
    gap : float, default 0.08
        Padding between bars of a group (band fraction).
    labels : bool, default False
        Value labels on the bars (they count when values change), where they fit a bar's width.
    prefix : str
        Before each bar's number in its label ('$').
    series : str
        The series within each group (default: the colour field).
    suffix : str
        After it ('M', ' kr').
    x : str
    x_type : str, default "band"
        (``xType``)
    y : str
    y_type : str, default "linear"
        (``yType``)

    Theme tokens: ``ink-2``, ``size.label``, ``radius.bar``.
    """
    return use('@datars/std/grouped', locals(), RENAMES['grouped'])


RENAMES['grouped'] = {"x_type": "xType", "y_type": "yType"}


def hemicycle(
    *,
    data: Any = None,
    align: Any = None,
    category: Any = None,
    rows: Any = None,
    total: Any = None,
    value: Any = None,
) -> Node:
    """A parliament: one dot per seat on concentric arcs, grouped by party left to right. Seats are
    keyed (party, Unit i).

    Recipe ``@datars/std/hemicycle``.

    Parameters
    ----------
    align : "middle" | "bottom", default "middle"
        In a box taller than it needs (a phone): centred up and down, or at the bottom (with a
        line of text right under it).
    category : str
    data : str | DataFrame | Data
    rows : float, default 0
        Rows of seats (0 = automatic).
    total : bool, default True
    value : str
        Seats per party.
    """
    return use('@datars/std/hemicycle', locals(), RENAMES['hemicycle'])


RENAMES['hemicycle'] = {}


def indexed(
    *,
    data: Any = None,
    x: Any = None,
    y: Any = None,
    base: Any = None,
    baseline: Any = None,
    color: Any = None,
    format: Any = None,
    labels: Any = None,
    percent: Any = None,
    series: Any = None,
    stroke: Any = None,
    width: Any = None,
    x_type: Any = None,
) -> Node:
    """Series rebased to their first visible row — 100 (or 0 %) — so instruments at any price
    compare as performance: one line per series with a baseline, each labelled at its end with
    its change. Filter the rows to a range and every line starts from the base again. Use with
    `format: "+.0%"` on the plot for `percent`.

    Recipe ``@datars/std/indexed``.

    Parameters
    ----------
    base : float, default 100
        The value every series starts at.
    baseline : bool, default True
        A rule at the base.
    color : str
        The plot's colour field (line and label inks).
    data : str | DataFrame | Data
        The rows to draw (default: the plot's).
    format : str, default "+.1%"
        Format of the change in end labels.
    labels : bool, default True
        Label each line's end: series and change (pushed apart so they never overlap).
    percent : bool, default False
        Change from the start (0 = no change, 0.1 = +10 %) instead of an index.
    series : str
        One line per series (default: the colour field).
    stroke : value | Expr
        Line ink (default: the colour scale, else $mark).
    width : float, default 0
        Stroke width (0 = the theme's).
    x : str
        The date field.
    x_type : str, default "band"
        `band`: trading days side by side, no weekend gaps (the plot's); `time`/`linear`: rows
        by value. (``xType``)
    y : str
        The price field (default: the plot's `y`).

    Theme tokens: ``mark``, ``ink-2``, ``size.label``.
    """
    return use('@datars/std/indexed', locals(), RENAMES['indexed'])


RENAMES['indexed'] = {"x_type": "xType"}


def legend(
    *,
    scale: Any = None,
    title: Any = None,
) -> Node:
    """A legend for a colour scale: a swatch and a label per entry, flowing in rows (spaced by the
    labels' widths, wrapping at the box edge).

    Recipe ``@datars/std/legend``.

    Parameters
    ----------
    scale : str, default "color"
    title : str

    Theme tokens: ``ink-2``, ``size.label``.
    """
    return use('@datars/std/legend', locals(), RENAMES['legend'])


RENAMES['legend'] = {}


def line(
    *,
    data: Any = None,
    x: Any = None,
    y: Any = None,
    clip: Any = None,
    color: Any = None,
    curve: Any = None,
    labels: Any = None,
    points: Any = None,
    selected: Any = None,
    series: Any = None,
    stroke: Any = None,
    width: Any = None,
    x_type: Any = None,
    y_scale: Any = None,
) -> Node:
    """One line per series (the colour field, or `series`), through x/y. Draws on as it enters.

    Recipe ``@datars/std/line``.

    Parameters
    ----------
    clip : bool, default False
        Clip the lines to the plot area (the end labels stay outside it).
    color : str
    curve : "linear" | "monotone-x" | "catmull-rom" | "step" | "step-before" | "step-after", default "monotone-x"
    data : str | DataFrame | Data
    labels : bool, default False
        Label each line at its last point (labels pushed apart so they never overlap).
    points : bool, default False
        Dots at the data points.
    selected : str
        A keyset signal: selected series stay strong, the others recede.
    series : str
        Group rows into lines by this field (default: the colour field).
    stroke : value | Expr
        Stroke ink or expression.
    width : float, default 0
        Stroke width (0 = the theme's stroke.line).
    x : str
    x_type : str, default "linear"
        (``xType``)
    y : str
    y_scale : str, default "y"
        The value scale: `y2` for a plot's right axis. (``yScale``)

    Theme tokens: ``mark``, ``stroke.line``, ``size.label``.
    """
    return use('@datars/std/line', locals(), RENAMES['line'])


RENAMES['line'] = {"x_type": "xType", "y_scale": "yScale"}


def map(
    *,
    data: Any = None,
    backdrop: Any = None,
    base: Any = None,
    camera: Any = None,
    chapter: Any = None,
    children: Any = None,
    color_type: Any = None,
    fill_opacity: Any = None,
    fit: Any = None,
    format: Any = None,
    key: Any = None,
    label: Any = None,
    labels: Any = None,
    legend: Any = None,
    padding: Any = None,
    projection: Any = None,
    regions: Any = None,
    sea: Any = None,
    selected: Any = None,
    source: Any = None,
    stops: Any = None,
    stroke: Any = None,
    under: Any = None,
    value: Any = None,
) -> Node:
    """A map: regions of a geo source, coloured by a data table joined on a key (choropleth), with
    neutral backdrop land, over which children (symbols, points, lines, annotations) draw in the
    same projection.

    Recipe ``@datars/std/map``.

    Parameters
    ----------
    backdrop : bool, default True
        Draw regions without data too (in $map.no-data); off: only regions with data.
    base : list[Node]
        Layers beneath everything, moving with the camera: a basemap (`basemap({ part: 'base'
        })`).
    camera : object
        A camera over the map: {fit: {keys: [...]} | {bbox: [x0, y0, x1, y1]}, padding} — bbox
        corners may be expressions like geo.x(lon, lat). Cameras fly between states; the
        projection stays.
    chapter : str
        Clicking a region enters this program chapter with the region's id (drill-down).
    children : list[Node]
        Layers drawn on top: symbols, geoPoints, geoLines, annotations.
    color_type : "sequential" | "diverging" | "categorical" | "piecewise", default "sequential"
        (``colorType``)
    data : str | DataFrame | Data
        Values per region (optional).
    fill_opacity : float
        Region opacity; default 0.85 over a `base` basemap (its streets and water show through),
        else 1. (``fillOpacity``)
    fit : object
        What the projection fits: {keys: [...]}, {bbox: [lon0, lat0, lon1, lat1]} or the whole
        source (default). A fit clips the map to its box.
    format : str, default ".1~f"
    key : str
        The data column holding region ids.
    label : value | Expr
        Region label (tooltip, accessible name): an expression over the region row; default
        `name: value`.
    labels : bool, default False
    legend : bool, default False
        A colour ramp (or swatches, for categorical colour) in the lower-left corner.
    padding : float, default 8
    projection : str, default "equal-earth"
        equal-earth, mercator, web-mercator, natural-earth, albers-usa, orthographic,
        sweref99tm, planar, …
    regions : bool, default True
        Draw the source's regions; off: only the layers (a camera beat over a basemap).
    sea : bool, default False
        Fill the map's box with $map.water first (the sea around atlas regions, in themes that
        colour it).
    selected : str
        A keyset signal: selected regions stay strong, the others recede.
    source : str | DataFrame | Data
        A geo source (GeoJSON, TopoJSON or an atlas like `countries`).
    stops : str
        Piecewise colour stops: '#22c55e 2 · #f5a524 4 · #f97362 6.5'.
    stroke : bool, default True
        Borders between regions.
    under : str | DataFrame | Data
        Another geo source drawn beneath as neutral land (countries around admin-1 regions).
    value : str
        The value to colour by.

    Theme tokens: ``map.land``, ``map.no-data``, ``map.border``, ``map.water``, ``sequential``, ``diverging``, ``categorical``.
    """
    return use('@datars/std/map', locals(), RENAMES['map'])


RENAMES['map'] = {"color_type": "colorType", "fill_opacity": "fillOpacity"}


def moving_average(
    *,
    data: Any = None,
    x: Any = None,
    y: Any = None,
    color: Any = None,
    full: Any = None,
    kind: Any = None,
    label: Any = None,
    series: Any = None,
    source: Any = None,
    stroke: Any = None,
    width: Any = None,
    window: Any = None,
    x_type: Any = None,
) -> Node:
    """A moving average of the plot's `y` (a closing price) as a line: simple (the mean of the last
    `window` rows) or exponential (span `window`). Computed over `source` — the whole history —
    when given, so the first day on show already has its full window. Shown in the plot's
    indicator key.

    Recipe ``@datars/std/movingAverage``.

    Parameters
    ----------
    color : str
        The plot's colour field (per-series inks).
    data : str | DataFrame | Data
        The rows to draw (default: the plot's).
    full : bool, default True
        Only full windows: no line until `window` rows (else the first rows average what there
        is).
    kind : "sma" | "ema", default "sma"
        Simple or exponential.
    label : str
        Name in the indicator key and to screen readers (default `SMA 20`).
    series : str
        One average per series (tickers).
    source : str | DataFrame | Data
        A longer history of the same rows to compute over (the chart shows only the rows of
        `data`).
    stroke : value | Expr
        Line ink (default: $accent, or the colour scale per series).
    width : float, default 1.5
        Stroke width.
    window : float, default 20
        Rows per window (trading days on a band scale): 20 ≈ a month, 50, 200.
    x : str
        The date field.
    x_type : str, default "band"
        `band`: trading days side by side, no weekend gaps (the plot's); `time`/`linear`: rows
        by value. (``xType``)
    y : str
        The averaged field (default: the plot's `y`).

    Theme tokens: ``accent``.
    """
    return use('@datars/std/movingAverage', locals(), RENAMES['movingAverage'])


RENAMES['movingAverage'] = {"x_type": "xType"}


def ohlc(
    *,
    data: Any = None,
    x: Any = None,
    y: Any = None,
    close: Any = None,
    colored: Any = None,
    down: Any = None,
    format: Any = None,
    high: Any = None,
    label: Any = None,
    low: Any = None,
    open: Any = None,
    up: Any = None,
    width: Any = None,
    x_type: Any = None,
) -> Node:
    """OHLC bars: per row a vertical line from low to high with the open ticked to the left and the
    close to the right, in `$up`/`$down` by direction (or ink). Same fields and plot fitting as
    `candlestick`.

    Recipe ``@datars/std/ohlc``.

    Parameters
    ----------
    close : str
        Closing price field (default: the plot's `y`, else `close`).
    colored : bool, default True
        Colour by direction; off: every bar in `$ink`.
    data : str | DataFrame | Data
        The rows to draw (default: the plot's).
    down : str, default "$down"
        Ink of falling bars.
    format : str, default ",.2f"
        Price format in labels.
    high : str, default "high"
        High field.
    label : value | Expr
        Bar label; default date · O H L C (change).
    low : str, default "low"
        Low field.
    open : str, default "open"
        Opening price field.
    up : str, default "$up"
        Ink of rising bars.
    width : float, default 0
        Tick span: a fraction of the band (0 = the band), px on a continuous scale.
    x : str
        The date (or time) field.
    x_type : str, default "band"
        `band`: trading days side by side, no weekend gaps (the plot's); `time`/`linear`: rows
        by value. (``xType``)
    y : str
        The plot's value field: the close, unless `close` is given.

    Theme tokens: ``up``, ``down``, ``ink``.
    """
    return use('@datars/std/ohlc', locals(), RENAMES['ohlc'])


RENAMES['ohlc'] = {"x_type": "xType"}


def pareto(
    *,
    data: Any = None,
    x: Any = None,
    y: Any = None,
    stroke: Any = None,
    x_type: Any = None,
) -> Node:
    """The running share of the total, from the largest category down, as a line with points on the
    plot's right axis (`right: { domain: [0, 1], format: '.0%' }`) — over bars sorted
    descending, a Pareto chart.

    Recipe ``@datars/std/pareto``.

    Parameters
    ----------
    data : str | DataFrame | Data
    stroke : value | Expr
        Line ink (default: the theme's secondary mark).
    x : str
    x_type : str, default "band"
        (``xType``)
    y : str

    Theme tokens: ``ink-2``.
    """
    return use('@datars/std/pareto', locals(), RENAMES['pareto'])


RENAMES['pareto'] = {"x_type": "xType"}


def pie(
    *,
    data: Any = None,
    category: Any = None,
    format: Any = None,
    inner: Any = None,
    labels: Any = None,
    pad: Any = None,
    sort: Any = None,
    total: Any = None,
    value: Any = None,
) -> Node:
    """Parts of a whole as slices (set `inner` > 0 for a donut). Colours from the categorical
    palette by category.

    Recipe ``@datars/std/pie``.

    Parameters
    ----------
    category : str
    data : str | DataFrame | Data
    format : str, default ".1~f"
    inner : float, default 0
        Inner radius as a fraction of the outer (0 = pie, 0.6 = donut).
    labels : bool, default True
    pad : float, default 0.006
        Pad angle between slices (radians).
    sort : "none" | "asc" | "desc", default "none"
    total : bool, default False
        Show the total in the middle (donuts).
    value : str

    Theme tokens: ``categorical``, ``paper``, ``ink``, ``muted``, ``size.label``, ``size.title``.
    """
    return use('@datars/std/pie', locals(), RENAMES['pie'])


RENAMES['pie'] = {}


def plot(
    *,
    data: Any = None,
    x: Any = None,
    y: Any = None,
    axes: Any = None,
    brush: Any = None,
    children: Any = None,
    clip: Any = None,
    color: Any = None,
    color_type: Any = None,
    format: Any = None,
    grid: Any = None,
    label_space: Any = None,
    legend: Any = None,
    lower: Any = None,
    nice: Any = None,
    padding: Any = None,
    prefix: Any = None,
    right: Any = None,
    stops: Any = None,
    subtitle: Any = None,
    suffix: Any = None,
    title: Any = None,
    x_domain: Any = None,
    x_format: Any = None,
    x_label: Any = None,
    x_ticks: Any = None,
    x_type: Any = None,
    y_domain: Any = None,
    y_format: Any = None,
    y_label: Any = None,
    y_ticks: Any = None,
    y_type: Any = None,
    zero: Any = None,
) -> Node:
    """A cartesian frame: x/y (and colour) scales from data, axes and gridlines sized by the
    engine, a title, and marks as children.

    Recipe ``@datars/std/plot``.

    Parameters
    ----------
    axes : "both" | "x" | "y" | "none", default "both"
    brush : str
        A signal to brush into: dragging across the plot selects a range of the category/time
        axis (see `brush()` and `brushed()`).
    children : list[Node]
        Marks and annotations.
    clip : bool, default False
        Clip marks to the plot area (for explicit domains narrower than the data: a zoom).
    color : str
        Field mapped to colour (categorical by default).
    color_type : "categorical" | "sequential" | "diverging" | "piecewise", default "categorical"
        (``colorType``)
    data : str | DataFrame | Data
        The table marks read by default.
    format : str
        Number format for value-axis labels.
    grid : bool, default True
        Gridlines along the value axis.
    label_space : float, default 110
        Room at the right (px) when a line child labels its ends. (``labelSpace``)
    legend : bool, default False
        A colour legend below the plot.
    lower : object
        A pane under the plot area on the same x with its own value axis, scale `lower`: {y,
        data?, height? (fraction or px, 0.22), format?, label?}. Marks go there with `yScale:
        "lower"`; a `volume` child makes one when it isn't given.
    nice : bool, default True
        Round linear domains to nice numbers.
    padding : float, default 0.22
        Band padding.
    prefix : str
        Before each value-axis number ('$').
    right : object
        A second value axis on the right, scale `y2`: {y, data?, domain?, label?, format?,
        prefix?, suffix?}. Marks use it with `yScale: "y2"`.
    stops : str
        Piecewise colour stops (colorType piecewise): '#bae6fd 7 · #0b1f3a 14.2'.
    subtitle : str
    suffix : str
        After it ('M', ' kr').
    title : str
        Title above the plot.
    x : str
        Field on the horizontal axis.
    x_domain : object
        Explicit x domain. (``xDomain``)
    x_format : str
        Number format for the x axis's labels, whichever axis holds the values: 'd' reads
        decimal years on a linear axis as whole years (a whole-number format labels whole-number
        ticks only). (``xFormat``)
    x_label : str
        (``xLabel``)
    x_ticks : float, default 0
        Tick count hint for the x axis (0 = from its length). (``xTicks``)
    x_type : "band" | "point" | "linear" | "log" | "sqrt" | "time", default "band"
        (``xType``)
    y : str
        Field on the vertical axis.
    y_domain : object
        Explicit y domain. (``yDomain``)
    y_format : str
        Number format for the y axis's labels (overrides `format` there). (``yFormat``)
    y_label : str
        (``yLabel``)
    y_ticks : float, default 0
        Tick count hint for the y axis (0 = from its length). (``yTicks``)
    y_type : "band" | "point" | "linear" | "log" | "sqrt" | "time", default "linear"
        (``yType``)
    zero : bool
        Include zero in the value axis's domain (default: yes; prices under candles, averages,
        bands and indexed lines fit their range instead).

    Theme tokens: ``ink``, ``muted``, ``grid``, ``rule``, ``size.title``, ``size.label``.
    """
    return use('@datars/std/plot', locals(), RENAMES['plot'])


RENAMES['plot'] = {"color_type": "colorType", "label_space": "labelSpace", "x_domain": "xDomain", "x_format": "xFormat", "x_label": "xLabel", "x_ticks": "xTicks", "x_type": "xType", "y_domain": "yDomain", "y_format": "yFormat", "y_label": "yLabel", "y_ticks": "yTicks", "y_type": "yType"}


def point(
    *,
    data: Any = None,
    x: Any = None,
    y: Any = None,
    clip: Any = None,
    color: Any = None,
    fill: Any = None,
    label: Any = None,
    opacity: Any = None,
    r: Any = None,
    symbol: Any = None,
    x_type: Any = None,
    y_type: Any = None,
) -> Node:
    """A dot per row (instanced: scales to 10⁵–10⁶ points).

    Recipe ``@datars/std/point``.

    Parameters
    ----------
    clip : bool, default False
        Clip to the plot area.
    color : str
    data : str | DataFrame | Data
    fill : value | Expr
    label : value | Expr
        Accessible label per point.
    opacity : value | Expr
    r : value | Expr
        Radius (px) or expression.
    symbol : str, default "circle"
    x : str
    x_type : str, default "linear"
        (``xType``)
    y : str
    y_type : str, default "linear"
        (``yType``)

    Theme tokens: ``mark``, ``point.radius``.
    """
    return use('@datars/std/point', locals(), RENAMES['point'])


RENAMES['point'] = {"x_type": "xType", "y_type": "yType"}


def route(
    *,
    data: Any = None,
    ink: Any = None,
    lat0: Any = None,
    lat1: Any = None,
    lon0: Any = None,
    lon1: Any = None,
    width: Any = None,
) -> Node:
    """Great-circle routes between two lon/lat points per row.

    Recipe ``@datars/std/route``.

    Parameters
    ----------
    data : str | DataFrame | Data
    ink : str, default "$accent@0.6"
    lat0 : str
    lat1 : str
    lon0 : str
    lon1 : str
    width : value | Expr
    """
    return use('@datars/std/route', locals(), RENAMES['route'])


RENAMES['route'] = {}


def rule(
    *,
    axis: Any = None,
    dashed: Any = None,
    ink: Any = None,
    label: Any = None,
    value: Any = None,
) -> Node:
    """A reference line at a value on the x or y scale (a target, an average, 'today').

    Recipe ``@datars/std/rule``.

    Parameters
    ----------
    axis : "x" | "y", default "y"
    dashed : bool, default True
    ink : str, default "$ink-2"
    label : str
    value : value | Expr
    """
    return use('@datars/std/rule', locals(), RENAMES['rule'])


RENAMES['rule'] = {}


def sankey(
    *,
    data: Any = None,
    label: Any = None,
    node_padding: Any = None,
    node_width: Any = None,
    selected: Any = None,
    source: Any = None,
    target: Any = None,
    value: Any = None,
) -> Node:
    """Flows between nodes: nodes in columns by depth, ribbons as wide as their flow. Links keep
    their row key (bars of the same rows morph into ribbons).

    Recipe ``@datars/std/sankey``.

    Parameters
    ----------
    data : str | DataFrame | Data
        One row per link.
    label : value | Expr
        Link label (tooltip, accessible name); default `source → target: value`.
    node_padding : float, default 12
        (``nodePadding``)
    node_width : float, default 14
        (``nodeWidth``)
    selected : str
        A keyset signal of node names: links touching them stay strong, the others recede.
    source : str
    target : str
    value : str
    """
    return use('@datars/std/sankey', locals(), RENAMES['sankey'])


RENAMES['sankey'] = {"node_padding": "nodePadding", "node_width": "nodeWidth"}


def slider(
    *,
    format: Any = None,
    label: Any = None,
    max: Any = None,
    min: Any = None,
    signal: Any = None,
    step: Any = None,
) -> Node:
    """A slider for a numeric signal: press or drag to set it (snapped to `step`). Shows the label
    and the current value.

    Recipe ``@datars/std/slider``.

    Parameters
    ----------
    format : str, default ",.0f"
        Value format.
    label : str, default ""
    max : float, default 100
    min : float, default 0
    signal : str
        The numeric signal it sets.
    step : float, default 0
        Snap step (0 = continuous).

    Theme tokens: ``accent``, ``rule``, ``ink-2``, ``size.label``.
    """
    return use('@datars/std/slider', locals(), RENAMES['slider'])


RENAMES['slider'] = {}


def span(
    *,
    axis: Any = None,
    from_: Any = None,
    ink: Any = None,
    label: Any = None,
    opacity: Any = None,
    to: Any = None,
) -> Node:
    """A shaded band between two values on the x or y scale (a recession, a target range).

    Recipe ``@datars/std/span``.

    Parameters
    ----------
    axis : "x" | "y", default "x"
    from_ : value | Expr
        (``from``)
    ink : str, default "$ink"
    label : str
    opacity : float, default 0.07
    to : value | Expr
    """
    return use('@datars/std/span', locals(), RENAMES['span'])


RENAMES['span'] = {"from_": "from"}


def sparkline(
    *,
    data: Any = None,
    x: Any = None,
    y: Any = None,
    dot: Any = None,
    fill: Any = None,
    format: Any = None,
    name: Any = None,
    stroke: Any = None,
    trend: Any = None,
    width: Any = None,
    x_type: Any = None,
) -> Node:
    """A sparkline: a word-sized line of `y` over `x` that fills its box (a table cell, a card) —
    no axes, the last value marked with a dot, coloured `$up` or `$down` by whether it ended
    above where it started. Works on any table, `@group` too (one per ticker in a repeat).

    Recipe ``@datars/std/sparkline``.

    Parameters
    ----------
    data : str | DataFrame | Data
        The rows (a named table, or `@group` inside a repeat).
    dot : bool, default True
        A dot at the last value.
    fill : bool, default True
        A soft area under the line.
    format : str, default ",.2f"
        Value format in the label.
    name : str
        What the line is (its accessible label starts with it).
    stroke : value | Expr
        Line ink (overrides the trend colour).
    trend : bool, default True
        Colour by the change over the line ($up / $down); off: $mark.
    width : float, default 1.5
        Stroke width.
    x : str
        The date (or order) field.
    x_type : "linear" | "time" | "point", default "point"
        x scale: `point` spaces rows evenly (trading days), `time` by date. (``xType``)
    y : str
        The value field.

    Theme tokens: ``up``, ``down``, ``mark``.
    """
    return use('@datars/std/sparkline', locals(), RENAMES['sparkline'])


RENAMES['sparkline'] = {"x_type": "xType"}


def stacked(
    *,
    data: Any = None,
    x: Any = None,
    y: Any = None,
    color: Any = None,
    format: Any = None,
    labels: Any = None,
    offset: Any = None,
    prefix: Any = None,
    segment_key: Any = None,
    series: Any = None,
    suffix: Any = None,
    x_type: Any = None,
    y_type: Any = None,
) -> Node:
    """Stacked bars: a segment per series in each category (offset `expand` for 100 %); horizontal
    when y is the band axis. Keys (series, x), shared with grouped bars and heatmap cells.

    Recipe ``@datars/std/stacked``.

    Parameters
    ----------
    color : str
    data : str | DataFrame | Data
    format : str, default ",.1~f"
        Number format of each segment's label (its value label, hover, screen readers).
    labels : bool, default False
        Value labels inside the segments (they count when values change), where they fit.
    offset : "zero" | "expand", default "zero"
    prefix : str
        Before the number ('$').
    segment_key : value | Expr
        Segment key (default the composite `(series, category)`, so segments merge into their
        series' bar); e.g. `d.party` so one 100 % bar's segments pair with that party's bar or
        slice. (``segmentKey``)
    series : str
    suffix : str
        After it ('M', ' kr').
    x : str
    x_type : str, default "band"
        (``xType``)
    y : str
    y_type : str, default "linear"
        (``yType``)

    Theme tokens: ``size.label``.
    """
    return use('@datars/std/stacked', locals(), RENAMES['stacked'])


RENAMES['stacked'] = {"segment_key": "segmentKey", "x_type": "xType", "y_type": "yType"}


def stripes(
    *,
    data: Any = None,
    x: Any = None,
    label: Any = None,
    mid: Any = None,
    value: Any = None,
) -> Node:
    """Colour stripes: one full-height band per ordered value, on a diverging scale around `mid`.

    Recipe ``@datars/std/stripes``.

    Parameters
    ----------
    data : str | DataFrame | Data
    label : value | Expr
        Stripe label (tooltip, accessible name); default `x: value`.
    mid : float, default 0
    value : str
    x : str
    """
    return use('@datars/std/stripes', locals(), RENAMES['stripes'])


RENAMES['stripes'] = {}


def swarm(
    *,
    data: Any = None,
    x: Any = None,
    color: Any = None,
    r: Any = None,
    x_type: Any = None,
) -> Node:
    """A beeswarm: every row a dot along one value axis, packed so none overlap (windowed neighbour
    search; 20k dots in about a second).

    Recipe ``@datars/std/swarm``.

    Parameters
    ----------
    color : str
    data : str | DataFrame | Data
    r : float, default 3.5
    x : str
    x_type : str, default "linear"
        (``xType``)
    """
    return use('@datars/std/swarm', locals(), RENAMES['swarm'])


RENAMES['swarm'] = {"x_type": "xType"}


def symbols(
    *,
    data: Any = None,
    fill: Any = None,
    format: Any = None,
    key: Any = None,
    label: Any = None,
    max: Any = None,
    r: Any = None,
    source: Any = None,
    stops: Any = None,
    value: Any = None,
) -> Node:
    """Proportional symbols: a circle per region (or point feature) at its visual centre, area ∝
    value — or all one size (`r`) without a value field.

    Recipe ``@datars/std/symbols``.

    Parameters
    ----------
    data : str | DataFrame | Data
    fill : value | Expr
    format : str, default ",.0f"
    key : str
    label : value | Expr
        Label per symbol (tooltip, accessible name); default `name: value`.
    max : float, default 28
        Largest radius (px).
    r : float, default 4
        Radius without a value field (px).
    source : str | DataFrame | Data
    stops : str
        Colour by value on piecewise stops ('#bae6fd 7 · #0b1f3a 14.2') instead of one fill.
    value : str
        Size by this field (omit for same-size dots).
    """
    return use('@datars/std/symbols', locals(), RENAMES['symbols'])


RENAMES['symbols'] = {}


def title(
    *,
    source: Any = None,
    subtitle: Any = None,
    text: Any = None,
) -> Node:
    """A title (and optional subtitle and source line).

    Recipe ``@datars/std/title``.

    Parameters
    ----------
    source : str
    subtitle : str
    text : str, default ""
    """
    return use('@datars/std/title', locals(), RENAMES['title'])


RENAMES['title'] = {}


def track(
    *,
    data: Any = None,
    future: Any = None,
    head: Any = None,
    ink: Any = None,
    lat: Any = None,
    lon: Any = None,
    time: Any = None,
    until: Any = None,
) -> Node:
    """A path over time (a storm, a flight): drawn up to `until` (a data-time signal) with a moving
    head.

    Recipe ``@datars/std/track``.

    Parameters
    ----------
    data : str | DataFrame | Data
    future : bool, default False
        Draw the whole path faintly underneath (where it will go).
    head : bool, default True
    ink : str, default "$negative"
    lat : str
    lon : str
    time : str
    until : value | Expr
        Data time to draw up to (e.g. the `year` signal).
    """
    return use('@datars/std/track', locals(), RENAMES['track'])


RENAMES['track'] = {}


def treemap(
    *,
    data: Any = None,
    category: Any = None,
    color: Any = None,
    color_type: Any = None,
    format: Any = None,
    labels: Any = None,
    stops: Any = None,
    value: Any = None,
) -> Node:
    """A squarified treemap: area ∝ value, one rectangle per category, labels where they fit.
    Coloured by category, or by a value on piecewise stops.

    Recipe ``@datars/std/treemap``.

    Parameters
    ----------
    category : str
    color : str
        Colour by this field (default: the category).
    color_type : "categorical" | "piecewise", default "categorical"
        (``colorType``)
    data : str | DataFrame | Data
    format : str, default ".1~f"
    labels : bool, default True
    stops : str
        Piecewise colour stops: '#bae6fd 7 · #0b1f3a 14.2'.
    value : str
    """
    return use('@datars/std/treemap', locals(), RENAMES['treemap'])


RENAMES['treemap'] = {"color_type": "colorType"}


def volume(
    *,
    data: Any = None,
    x: Any = None,
    y: Any = None,
    close: Any = None,
    colored: Any = None,
    down: Any = None,
    format: Any = None,
    opacity: Any = None,
    open: Any = None,
    up: Any = None,
    volume: Any = None,
    width: Any = None,
    x_type: Any = None,
    y_scale: Any = None,
) -> Node:
    """Volume bars under a price chart: in a plot, they go to a pane below the price area that
    shares its x axis and has its own value axis (the plot's `lower` pane, made for them when
    not given), coloured like their day's candle.

    Recipe ``@datars/std/volume``.

    Parameters
    ----------
    close : str
        Closing price field (default: the plot's `y`, else `close`).
    colored : bool, default True
        Colour by the day's direction; off: `$muted`.
    data : str | DataFrame | Data
        The rows to draw (default: the plot's).
    down : str, default "$down"
        Ink on falling days.
    format : str, default ",.0f"
        Volume format in labels.
    opacity : float, default 0.55
        Bar opacity (volume recedes behind price).
    open : str, default "open"
        Opening price field (for the colour).
    up : str, default "$up"
        Ink on rising days.
    volume : str, default "volume"
        Volume field.
    width : float, default 0
        Bar width: a fraction of the band (0 = the band), px on a continuous scale.
    x : str
        The date field.
    x_type : str, default "band"
        `band`: trading days side by side, no weekend gaps (the plot's); `time`/`linear`: rows
        by value. (``xType``)
    y : str
        The plot's value field: the close, unless `close` is given.
    y_scale : str, default "lower"
        The value scale: `lower` (the plot's lower pane), or `y` for a volume chart of its own.
        (``yScale``)

    Theme tokens: ``up``, ``down``, ``muted``.
    """
    return use('@datars/std/volume', locals(), RENAMES['volume'])


RENAMES['volume'] = {"x_type": "xType", "y_scale": "yScale"}


def waffle(
    *,
    data: Any = None,
    category: Any = None,
    columns: Any = None,
    gap: Any = None,
    rows: Any = None,
    value: Any = None,
) -> Node:
    """One square per unit (e.g. per percentage point). Units are keyed (category, Unit i), so bars
    split into squares and back.

    Recipe ``@datars/std/waffle``.

    Parameters
    ----------
    category : str
    columns : float, default 10
    data : str | DataFrame | Data
    gap : float, default 2
    rows : float, default 10
    value : str
    """
    return use('@datars/std/waffle', locals(), RENAMES['waffle'])


RENAMES['waffle'] = {}


def waterfall(
    *,
    data: Any = None,
    x: Any = None,
    y: Any = None,
    format: Any = None,
    prefix: Any = None,
    suffix: Any = None,
    total: Any = None,
    x_type: Any = None,
    y_type: Any = None,
) -> Node:
    """A waterfall/bridge: each change floats from the running total; rows marked as totals (a
    boolean field, or keys starting with '=') are bars from zero.

    Recipe ``@datars/std/waterfall``.

    Parameters
    ----------
    data : str | DataFrame | Data
    format : str, default ",.0f"
    prefix : str
        Before each label's number ('$').
    suffix : str
        After it ('M', ' kr').
    total : str
    x : str
    x_type : str, default "band"
        (``xType``)
    y : str
    y_type : str, default "linear"
        (``yType``)
    """
    return use('@datars/std/waterfall', locals(), RENAMES['waterfall'])


RENAMES['waterfall'] = {"x_type": "xType", "y_type": "yType"}


__all__ = ['annotate', 'area', 'attribution', 'axis', 'bar', 'basemap', 'bollinger', 'calendar', 'candlestick', 'card', 'cell', 'cloud', 'dot', 'dot_density', 'drawdown', 'facet', 'funnel', 'geo_lines', 'geo_points', 'grid', 'grouped', 'hemicycle', 'indexed', 'legend', 'line', 'map', 'moving_average', 'ohlc', 'pareto', 'pie', 'plot', 'point', 'route', 'rule', 'sankey', 'slider', 'span', 'sparkline', 'stacked', 'stripes', 'swarm', 'symbols', 'title', 'track', 'treemap', 'volume', 'waffle', 'waterfall', "RECIPES", "RENAMES"]
