// Closest.
// Swing-state margins, points (Trump − Harris), closest first.
// Sources and rounding: the article's notes on the data.
import { doc, data, e, group, motion, op, signal, step, story, table } from "@datars/sdk";
import { bar, card, plot } from "@datars/std";
import { civic } from "../theme";

export default doc({
  id: "us-election-2024/closest",
  title: "Closest",
  size: [960, 420],
  theme: civic,
  data: {
    swing: data.values({
      label: ["US-AZ", "US-GA", "US-MI", "US-NV", "US-NC", "US-PA", "US-WI"],
      value: [5.5, 2.2, 1.4, 3.1, 3.2, 1.7, 0.9],
    }, { key: "label" }),
  },
  tables: { swing_1: table("swing", op.sort("value")) },
  signals: { scene: signal.str("c") },
  keys: {
    Democratic: { color: "#2563eb" },
    Harris: { color: "#2563eb" },
    Others: { color: "#9aa3ad" },
    Republican: { color: "#c0392b" },
    Trump: { color: "#c0392b" },
    "US-AK": { color: "#c0392b" },
    "US-AL": { color: "#c0392b" },
    "US-AR": { color: "#c0392b" },
    "US-AZ": { name: "Arizona", color: "#c0392b" },
    "US-CA": { color: "#2563eb" },
    "US-CO": { color: "#2563eb" },
    "US-CT": { color: "#2563eb" },
    "US-DC": { color: "#2563eb" },
    "US-DE": { color: "#2563eb" },
    "US-FL": { color: "#c0392b" },
    "US-GA": { name: "Georgia", color: "#c0392b" },
    "US-HI": { color: "#2563eb" },
    "US-IA": { color: "#c0392b" },
    "US-ID": { color: "#c0392b" },
    "US-IL": { color: "#2563eb" },
    "US-IN": { color: "#c0392b" },
    "US-KS": { color: "#c0392b" },
    "US-KY": { color: "#c0392b" },
    "US-LA": { color: "#c0392b" },
    "US-MA": { color: "#2563eb" },
    "US-MD": { color: "#2563eb" },
    "US-ME": { color: "#2563eb" },
    "US-MI": { name: "Michigan", color: "#c0392b" },
    "US-MN": { color: "#2563eb" },
    "US-MO": { color: "#c0392b" },
    "US-MS": { color: "#c0392b" },
    "US-MT": { color: "#c0392b" },
    "US-NC": { name: "North Carolina", color: "#c0392b" },
    "US-ND": { color: "#c0392b" },
    "US-NE": { color: "#c0392b" },
    "US-NH": { color: "#2563eb" },
    "US-NJ": { color: "#2563eb" },
    "US-NM": { color: "#2563eb" },
    "US-NV": { name: "Nevada", color: "#c0392b" },
    "US-NY": { color: "#2563eb" },
    "US-OH": { color: "#c0392b" },
    "US-OK": { color: "#c0392b" },
    "US-OR": { color: "#2563eb" },
    "US-PA": { name: "Pennsylvania", color: "#c0392b" },
    "US-RI": { color: "#2563eb" },
    "US-SC": { color: "#c0392b" },
    "US-SD": { color: "#c0392b" },
    "US-TN": { color: "#c0392b" },
    "US-TX": { color: "#c0392b" },
    "US-UT": { color: "#c0392b" },
    "US-VA": { color: "#2563eb" },
    "US-VT": { color: "#2563eb" },
    "US-WA": { color: "#2563eb" },
    "US-WI": { name: "Wisconsin", color: "#c0392b" },
    "US-WV": { color: "#c0392b" },
    "US-WY": { color: "#c0392b" },
  },
  scene: group({
    key: "root",
    layout: { type: "stack", padding: [16, 20, 12, 12] },
    children: [
      plot({
        data: "swing_1",
        x: "value",
        y: "label",
        color: "value",
        xType: "linear",
        yType: "band",
        colorType: "piecewise",
        title: "Trump's margin in the seven swing states, percentage points",
        format: ",.1~f",
        padding: 0.25,
        stops: "#fca5a5 0.9 · #7f1d1d 5.5",
        children: [bar({ format: ",.1~f", labels: true })],
      }, { key: "chart", when: e('scene == "c"') }),
      card({ text: "Wisconsin, the closest, was decided by under one point.", at: "auto", width: 260 }, {
        key: "caption",
        when: e('scene == "c"'),
      }),
    ],
  }),
  motion: motion(
    { select: { role: "datum" }, matcher: "by-key" },
    { select: { role: "region" }, matcher: "by-key" },
    { select: { kind: "instance" }, matcher: "by-key" },
  ),
  program: story({
    steps: [step("c", { set: { scene: "c" }, text: "Wisconsin, the closest, was decided by under one point." })],
    drivers: ["autoplay"],
  }),
});
