// The "Big data" family: 100,000 taxi pickups in a made-up city, generated by the engine from a few
// seeded expressions (nothing to download), counted into hexagons and grid cells, cut into density
// contours and drawn as a point cloud — the engine bins the rows once, frames draw the bins. Then a
// year of weekly temperatures at 1,000 weather stations, every series a faint line.
import { doc, data, e, group, motion, story, step, text } from "@datars/sdk";
import { plot, hexbin, heatmap2d, contours, cloud, manyLines } from "@datars/std";

const where = {
  id: e("d.i"),
  p: e("rand(d.i, 1) < 0.38 ? 0 : rand(d.i, 1) < 0.52 ? 1 : rand(d.i, 1) < 0.6 ? 2 : rand(d.i, 1) < 0.78 ? 3 : 4"),
  t: e("rand(d.i, 2) * 2 - 1"),
  x: e("round([0, 3, -7.5, d.t * 9, 0][d.p] + randn(d.i, 3) * [1.8, 0.35, 0.45, 0.22, 4.5][d.p], 3)"),
  north: e("round([0, -1.5, 5, d.t * 5 - 1, 0][d.p] + randn(d.i, 4) * [1.4, 0.35, 0.45, 0.22, 3.5][d.p], 3)"),
};
const pickups = data.generate(100_000, { ...where, y: e("d.north") }, { keep: ["id", "x", "y"], key: "id" });
// The same rows again for the cloud, whose view has y growing downwards like the screen (north up
// needs it flipped) — and a source of its own: publishing turns a cloud's source into a point
// archive read by range, which the binning recipes can't read as a table.
const points = data.generate(100_000, { ...where, y: e("-d.north") }, { keep: ["id", "x", "y"], key: "id" });
const weeks = data.generate(52_000, {
  s: e("floor(d.i / 52)"),
  week: e("d.i % 52 + 1"),
  station: e('"Station " + (d.s + 1)'),
  temp: e("round(9 + randn(d.s, 1) * 5 - (7 + rand(d.s, 2) * 7) * cos(6.2832 * (d.week - 3) / 52) + randn(d.i, 3) * 1.6, 1)"),
}, { keep: ["station", "week", "temp"], key: ["station", "week"] });
const extent = [-10, -7, 10, 7];
const at = (state: string) => ({ key: "chart", when: e(`state == "${state}"`) });
const title = "100,000 taxi pickups in a made-up city";
const frame = { data: "pickups", x: "x", y: "y", xType: "linear", zero: false, xDomain: [extent[0], extent[2]], yDomain: [extent[1], extent[3]], clip: true, grid: false, title, xLabel: "km east", yLabel: "km north" } as const;
const named = { name: "100,000 pickups", unit: "pickups" };

export default doc({
  title: "Big data, drawn by what it adds up to",
  description: "100,000 generated taxi pickups as hexagonal bins, a grid of cells, density contours and a sampled point cloud; then a year of weekly temperatures at 1,000 weather stations as faint lines.",
  size: [640, 400],
  data: { pickups, points, weeks },
  motion: motion({ duration: 1.0 }),
  scene: group({
    key: "root",
    layout: { type: "stack", padding: [14, 18, 10, 10] },
    children: [
      plot({ ...frame, children: [hexbin({ extent, radius: 11, ...named })] }, at("hexbin")),
      plot({ ...frame, children: [heatmap2d({ extent, cell: 10, ...named })] }, at("grid")),
      plot({ ...frame, children: [contours(named)] }, at("contours")),
      group({ key: "chart", when: e('state == "cloud"'), layout: { type: "rows", gap: 4 }, children: [
        text(title, [0, 0], { key: "title", size: { h: "auto" }, style: { font: "font.title", size: "$size.title", ink: "$ink", baseline: "top" } }),
        cloud({ data: "points", x: "x", y: "y", bbox: [-10, -7, 10, 7], points: 20_000, r: 1.2, name: "100,000 pickups" }),
      ] }),
      plot({ data: "weeks", x: "week", y: "temp", xType: "linear", zero: false, xDomain: [1, 52], title: "A year at 1,000 weather stations", xLabel: "week", yLabel: "weekly mean, °C", labelSpace: 90,
        children: [manyLines({ series: "station", name: "1,000 weather stations", highlight: "Station 417" })] }, at("lines")),
    ],
  }),
  program: story({
    steps: [
      step("hexbin", { title: "hexbin()", text: "Every pickup counted into hexagons a few pixels across." }),
      step("grid", { title: "heatmap2d()", text: "The same rows counted into a grid of cells." }),
      step("contours", { title: "contours()", text: "Their density, cut into nested levels." }),
      step("cloud", { title: "cloud()", text: "A sample of the points themselves — drag and pinch to explore; zoomed in, every row is drawn." }),
      step("lines", { title: "manyLines()", text: "52,000 rows as 1,000 faint lines, one picked out." }),
    ],
  }),
});
