"""Generate ``src/datars/std.py`` from the recipes' own descriptions.

The standard library is TypeScript (``packages/std``); every recipe describes its parameters,
defaults and theme tokens (``datars describe --json``). This script turns that description into
typed Python wrappers, so the Python surface is the std surface — never a parallel chart model —
and stays in sync by construction:

    python tools/gen_std.py              # regenerate std.py from the checked-in _recipes.json
    python tools/gen_std.py --refresh    # first refresh _recipes.json from `datars describe --json`

``tests/test_std_sync.py`` fails when std.py is stale against _recipes.json, and (when a CLI is
available) when _recipes.json is stale against the CLI's std.
"""

from __future__ import annotations

import argparse
import json
import keyword
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RECIPES = ROOT / "src" / "datars" / "_recipes.json"
OUT = ROOT / "src" / "datars" / "std.py"

# How a Python value for each param type is described in docstrings.
PY_TYPES = {
    "table": "str | DataFrame | Data",
    "field": "str",
    "number": "float",
    "string": "str",
    "bool": "bool",
    "ink": "str",
    "prop": "value | Expr",
    "enum": "str",
    "children": "list[Node]",
    "json": "object",
}


def snake(name: str) -> str:
    """camelCase → snake_case (``xType`` → ``x_type``); Python keywords get a trailing ``_``."""
    s = re.sub(r"(?<=[a-z0-9])([A-Z])", r"_\1", name).lower()
    return s + "_" if keyword.iskeyword(s) else s


def load_recipes(refresh: bool, cli: str | None) -> dict:
    if refresh:
        exe = cli or "datars"
        out = subprocess.run([exe, "describe", "--json"], check=True, capture_output=True, text=True).stdout
        data = json.loads(out)
        RECIPES.write_text(json.dumps(data, indent=2, sort_keys=True, ensure_ascii=False) + "\n", encoding="utf-8")
    return json.loads(RECIPES.read_text(encoding="utf-8"))


def fmt_default(v) -> str:
    """A default as Python spells it (``False``, ``"band"``, ``0.85``)."""
    if isinstance(v, bool) or v is None:
        return repr(v)
    return json.dumps(v, ensure_ascii=False)


def wrap(text: str, indent: str, width: int = 96) -> list[str]:
    words, lines, line = text.split(), [], ""
    for w in words:
        if line and len(indent) + len(line) + 1 + len(w) > width:
            lines.append(indent + line)
            line = w
        else:
            line = f"{line} {w}" if line else w
    if line:
        lines.append(indent + line)
    return lines or [indent]


def generate(recipes: dict) -> str:
    out = [
        '"""The standard library\'s recipes as Python functions — generated, do not edit.',
        "",
        "Generated by ``tools/gen_std.py`` from ``_recipes.json`` (``datars describe --json``): one function",
        "per ``@datars/std`` recipe, with its parameters, defaults and theme tokens. Each returns a",
        ":class:`~datars.Node` — a ``use`` node of the document IR, the same JSON the TypeScript SDK",
        "writes — which the engine expands. Parameters are keyword-only and snake_case (``x_type`` is",
        "the recipe's ``xType``); ``None`` means \"the recipe's default\". Table parameters take a table",
        "name, a DataFrame or :func:`datars.data`; prop parameters take a value or :func:`datars.e`.",
        "",
        "    import datars as dr",
        "    node = dr.std.pie(data=df, category=\"party\", value=\"share\", inner=0.6)",
        "    dr.chart(node)          # a displayable Chart",
        "",
        "Node options (``key``, ``when``, ``size``, …) go through :meth:`Node.opts`.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "import json",
        "from pathlib import Path",
        "from typing import Any",
        "",
        "from ._node import Node, use",
        "",
        "#: Every recipe's description by short name, as ``datars describe --json`` prints it.",
        "RECIPES: dict[str, dict] = {",
        "    rid.rsplit(\"/\", 1)[-1]: spec",
        "    for rid, spec in json.loads((Path(__file__).parent / \"_recipes.json\").read_text(encoding=\"utf-8\")).items()",
        "}",
        "",
        "#: Python parameter name → recipe parameter name, per recipe (where they differ).",
        "RENAMES: dict[str, dict[str, str]] = {}",
        "",
    ]
    names = []
    for rid in sorted(recipes):
        r = recipes[rid]
        name = rid.rsplit("/", 1)[-1]
        names.append(name)
        params = r.get("params", {})
        renames = {snake(p): p for p in params if snake(p) != p}
        sig = []
        for p in sorted(params, key=lambda p: (p not in ("data", "x", "y"), snake(p))):
            sig.append(f"    {snake(p)}: Any = None,")
        out.append("")
        out.append(f"def {snake(name)}(")
        if sig:
            out.append("    *,")
            out.extend(sig)
        out.append(") -> Node:")
        summary = wrap(" ".join((r.get("doc") or name).split()), "    ")
        out.append('    """' + summary[0].lstrip())
        out.extend(summary[1:])
        out.append("")
        out.append(f"    Recipe ``{rid}``.")
        if params:
            out.append("")
            out.append("    Parameters")
            out.append("    ----------")
            for p in sorted(params, key=snake):
                spec = params[p]
                ty = spec.get("type", "json")
                desc = PY_TYPES.get(ty, ty)
                if ty == "enum" and spec.get("values"):
                    desc = " | ".join(fmt_default(v) for v in spec["values"])
                head = f"    {snake(p)} : {desc}"
                if "default" in spec and spec["default"] not in (None, []):
                    head += f", default {fmt_default(spec['default'])}"
                out.append(head)
                text = spec.get("doc") or ""
                if snake(p) != p:
                    text = (text + f" (``{p}``)").strip()
                if text:
                    out.extend(wrap(text, "        "))
        if r.get("tokens"):
            out.append("")
            out.append("    Theme tokens: " + ", ".join(f"``{t}``" for t in r["tokens"]) + ".")
        out.append('    """')
        out.append(f"    return use({rid!r}, locals(), RENAMES[{name!r}])")
        out.append("")
        out.append("")
        out.append(f"RENAMES[{name!r}] = {json.dumps(renames, sort_keys=True)}")
        out.append("")
    out.append("")
    out.append("__all__ = [" + ", ".join(repr(snake(n)) for n in names) + ", \"RECIPES\", \"RENAMES\"]")
    out.append("")
    return "\n".join(out)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--refresh", action="store_true", help="refresh _recipes.json from `datars describe --json` first")
    ap.add_argument("--cli", help="the datars executable (default: datars on PATH)")
    ap.add_argument("--check", action="store_true", help="exit 1 if std.py is stale (don't write)")
    a = ap.parse_args(argv)
    src = generate(load_recipes(a.refresh, a.cli))
    if a.check:
        if OUT.read_text(encoding="utf-8") != src:
            print("std.py is stale: run python tools/gen_std.py", file=sys.stderr)
            return 1
        return 0
    OUT.write_text(src, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} ({src.count(chr(10))} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
