//! Smaller commands for authors and agents (docs/14): `new`, `describe`, `migrate`, `diff` and
//! `bundle inspect`. Each returns text for a terminal or JSON with `--json`.

use serde_json::{json, Value};
use std::collections::BTreeMap;

// ---- datars new / datars theme --specimen -------------------------------------------------

// The templates and the specimen board live in `datars-devtools`, so every client of the open
// tools (the CLI, the MCP server, a visual editor) starts from the same documents.
pub use datars_devtools::specimen::specimen_doc;
pub use datars_devtools::templates::new_doc;

// ---- datars describe -----------------------------------------------------------------------

/// Every std recipe (id → description), or one (`std/bar`, `bar` or `@datars/std/bar`).
pub fn describe(all: &BTreeMap<String, Value>, which: Option<&str>, json_out: bool) -> Result<String, String> {
    let Some(w) = which else {
        if json_out {
            return Ok(serde_json::to_string_pretty(all).unwrap_or_default());
        }
        let mut s = String::new();
        for (id, d) in all {
            let doc = d["doc"].as_str().unwrap_or("");
            let first = doc.split(". ").next().unwrap_or(doc).trim_end_matches('.');
            s += &format!("{:<28} {first}\n", id.trim_start_matches("@datars/"));
        }
        return Ok(s);
    };
    let id = format!("@datars/std/{}", w.trim_start_matches("@datars/").trim_start_matches("std/"));
    let d = all.get(&id).ok_or_else(|| format!("no recipe `{id}` (datars describe lists them)"))?;
    if json_out {
        return Ok(serde_json::to_string_pretty(d).unwrap_or_default());
    }
    let mut s = format!("{id}\n{}\n\nparams:\n", d["doc"].as_str().unwrap_or(""));
    for (name, p) in d["params"].as_object().into_iter().flatten() {
        let ty = p["type"].as_str().unwrap_or("?");
        let def = p.get("default").map(|v| format!(" = {v}")).unwrap_or_default();
        let doc = p["doc"].as_str().map(|d| format!("  — {d}")).unwrap_or_default();
        s += &format!("  {name}: {ty}{def}{doc}\n");
    }
    if let Some(t) = d["tokens"].as_array().filter(|t| !t.is_empty()) {
        s += &format!("\ntheme tokens: {}\n", t.iter().filter_map(|v| v.as_str()).collect::<Vec<_>>().join(", "));
    }
    Ok(s)
}

// ---- datars docs ---------------------------------------------------------------------------

fn first_sentence(doc: &str) -> &str {
    let end = doc.find(". ").map(|i| i + 1).unwrap_or(doc.len());
    doc[..end].trim_end_matches('.').trim()
}

/// The standard library reference, generated from the recipes' own descriptions (params,
/// defaults, docs, theme tokens) — it can't drift from the code.
pub fn reference_md(all: &BTreeMap<String, Value>) -> String {
    let mut s = String::from("# Standard library reference\n\n*Generated by `datars docs` from the recipes themselves — do not edit.* Every recipe is TypeScript in `packages/std/src`, written against the public SDK; `datars eject std/<name>` copies one into your project.\n\n");
    for id in all.keys() {
        let short = id.trim_start_matches("@datars/std/");
        s += &format!("- [`{short}`](#{short})\n");
    }
    for (id, d) in all {
        let short = id.trim_start_matches("@datars/std/");
        s += &format!("\n## {short}\n\n`{id}` — {}\n\n", d["doc"].as_str().unwrap_or(""));
        let params = d["params"].as_object();
        if params.is_some_and(|p| !p.is_empty()) {
            s += "| param | type | default | |\n|---|---|---|---|\n";
            for (name, p) in params.into_iter().flatten() {
                let def = p.get("default").map(|v| format!("`{v}`")).unwrap_or_default();
                let doc = p["doc"].as_str().unwrap_or("").replace('|', "\\|");
                s += &format!("| `{name}` | {} | {def} | {doc} |\n", p["type"].as_str().unwrap_or(""));
            }
        }
        if let Some(t) = d["tokens"].as_array().filter(|t| !t.is_empty()) {
            s += &format!("\nTheme tokens: {}\n", t.iter().filter_map(|v| v.as_str()).map(|t| format!("`{t}`")).collect::<Vec<_>>().join(", "));
        }
    }
    s
}

/// A compact index for coding agents (llms.txt style): what datars is, how to author and check a
/// chart, every command, every recipe in a line, and where the docs are.
pub fn llms_txt(all: &BTreeMap<String, Value>, help: &str) -> String {
    let mut s = String::from(
        r#"# datars

> A deterministic, multi-platform engine for data graphics. A chart is a document — `frame = F(doc, data, signals, t)` — rendered identically on the web, iOS, Android, desktop, in video and static exports. Charts are authored in TypeScript (`@datars/sdk` + `@datars/std`) or as JSON IR, and delivered as small content-addressed bundles to runtimes installed once.

## Author a chart

```ts
import { doc, data, group } from "@datars/sdk";
import { plot, bar } from "@datars/std";

export default doc({
  id: "sales", title: "Sales by region", size: [720, 420],
  data: { sales: data.values({ region: ["N", "S"], sales: [120, 98] }, { key: "region" }) },
  scene: group({ key: "root", layout: { type: "stack", padding: [16, 20, 12, 12] },
    children: [plot({ data: "sales", x: "region", y: "sales", children: [bar({ labels: true })] })] }),
});
```

Start from a template: `datars new mychart --template chart|story|explorable|map`.

Loop: `datars check doc.ts` (diagnostics) → `datars render doc.ts --state N` (look at the PNG) → `datars film doc.ts --from A --to B` (motion) → `datars lint doc.ts` → `datars explain doc.ts --key '("SE",)'` (why an element looks as it does) → `datars test` (goldens). The same tools are MCP tools (`datars-mcp`).

Rules of thumb: every data row has a key (identity carries marks through transitions); colours are theme tokens (`$accent`, `$categorical[3]`), not literals; program states set signals, marks read them in expressions (`=d.share * income / 100`); bare names are signals, `d.x` is the row.

## Commands

```
"#,
    );
    s += help.trim_start_matches("datars — deterministic data graphics\n").trim();
    s += &format!("\n```\n\n## Standard library ({} recipes)\n\n", all.len());
    for (id, d) in all {
        s += &format!("- `std/{}`: {}\n", id.trim_start_matches("@datars/std/"), first_sentence(d["doc"].as_str().unwrap_or("")));
    }
    s += "\nFull parameters: docs/reference/std.md (`datars describe std/<name>`).\n\n## Docs\n\n- docs/README.md — the design in one page; docs/02-principles.md first\n- docs/04-primitives.md, 05-time-and-motion.md, 06-data-and-reactivity.md, 08-programs.md, 09-geo.md — the model\n- docs/12-delivery.md — bundles, tiers, publishing; docs/18-themes.md — themes\n- docs/14-devtools-and-agents.md — tools and the agent workflow\n- docs/19-status.md — what is built and how it is verified\n- examples/ — small runnable documents, each also a golden test\n";
    s
}

/// The IR's JSON Schema, pretty-printed (`docs/reference/ir.schema.json`).
pub fn schema_json() -> String {
    serde_json::to_string_pretty(&datars_ir::json_schema()).unwrap_or_default() + "\n"
}

// ---- datars migrate ------------------------------------------------------------------------

/// Upgrade a document to the current IR: the changes made and the fields the IR ignores.
pub fn migrate(json_text: &str) -> Result<(Value, Vec<String>, Vec<String>), String> {
    let mut v: Value = serde_json::from_str(json_text).map_err(|e| e.to_string())?;
    let notes = datars_ir::migrate::migrate(&mut v);
    let ignored = datars_ir::migrate::ignored_fields(&v);
    Ok((v, notes, ignored))
}

// ---- datars diff ---------------------------------------------------------------------------

/// Every node's snapshot line by key path.
fn lines(scene: &datars_scene::Scene) -> BTreeMap<String, String> {
    fn go(n: &datars_scene::Node, path: &str, out: &mut BTreeMap<String, String>) {
        let here = if path.is_empty() { n.key.to_string() } else { format!("{path}/{}", n.key) };
        out.insert(here.clone(), n.snapshot_line());
        for c in n.children() {
            go(c, &here, out);
        }
    }
    let mut out = BTreeMap::new();
    go(&scene.root, "", &mut out);
    out
}

/// Element-level differences between two scenes: added, removed and changed nodes by key path.
pub fn diff(a: &datars_scene::Scene, b: &datars_scene::Scene) -> Value {
    let (la, lb) = (lines(a), lines(b));
    let added: Vec<Value> = lb.iter().filter(|(k, _)| !la.contains_key(*k)).map(|(k, l)| json!({ "path": k, "node": l })).collect();
    let removed: Vec<Value> = la.iter().filter(|(k, _)| !lb.contains_key(*k)).map(|(k, l)| json!({ "path": k, "node": l })).collect();
    let changed: Vec<Value> = la.iter().filter_map(|(k, l)| lb.get(k).filter(|m| *m != l).map(|m| json!({ "path": k, "from": l, "to": m }))).collect();
    json!({ "added": added, "removed": removed, "changed": changed, "same": la.keys().filter(|k| lb.get(*k) == la.get(*k)).count() })
}

pub fn diff_text(d: &Value) -> String {
    let mut s = String::new();
    for (sign, key) in [("+", "added"), ("-", "removed")] {
        for e in d[key].as_array().into_iter().flatten() {
            s += &format!("{sign} {}  {}\n", e["path"].as_str().unwrap_or(""), e["node"].as_str().unwrap_or("").trim());
        }
    }
    for e in d["changed"].as_array().into_iter().flatten() {
        s += &format!("~ {}\n    {}\n  → {}\n", e["path"].as_str().unwrap_or(""), e["from"].as_str().unwrap_or("").trim(), e["to"].as_str().unwrap_or("").trim());
    }
    let n = |k: &str| d[k].as_array().map_or(0, |a| a.len());
    s += &format!("{} added, {} removed, {} changed, {} unchanged\n", n("added"), n("removed"), n("changed"), d["same"]);
    s
}

// ---- datars bundle inspect -----------------------------------------------------------------

/// A bundle's variants and chunks (raw and gzipped), and which variant each kind of runtime picks.
pub fn bundle_inspect(bytes: &[u8]) -> Result<Value, String> {
    let b = datars_bundle::from_single_file(bytes).map_err(|e| e.to_string())?;
    let m = &b.manifest;
    let gz = |c: &[u8]| {
        use std::io::Write;
        let mut e = flate2::write::GzEncoder::new(Vec::new(), flate2::Compression::best());
        let _ = e.write_all(c);
        e.finish().map(|v| v.len()).unwrap_or(0)
    };
    let variants: Vec<Value> = m
        .variants
        .iter()
        .map(|v| {
            let entry: Value = b.chunks.get(&v.entry).and_then(|c| serde_json::from_slice(c).ok()).unwrap_or_default();
            let hashes: Vec<&str> = entry["chunks"].as_array().into_iter().flatten().filter_map(|h| h.as_str()).collect();
            let kinds: Vec<String> = hashes.iter().filter_map(|h| m.chunk(h)).map(|c| c.kind.clone()).collect();
            let raw: usize = hashes.iter().filter_map(|h| b.chunks.get(*h)).map(|c| c.len()).sum();
            let zipped: usize = hashes.iter().filter_map(|h| b.chunks.get(*h)).map(|c| gz(c)).sum();
            json!({ "tier": format!("{:?}", v.tier), "requires": v.requires, "chunks": kinds, "bytes": raw, "gzip": zipped })
        })
        .collect();
    let caps = |modules: &[&str], script: bool| {
        let mut c = datars_engine::bundle::capabilities(script, Vec::new());
        c.modules = modules.iter().map(|m| m.to_string()).collect();
        if !script {
            c.packages.clear();
        }
        c
    };
    let profiles = [
        ("web (core engine)", caps(&["core", "graph"], false)),
        ("web (full engine)", caps(&["core", "graph", "sandbox"], true)),
        ("app (DatarsKit / Android, script allowed)", caps(&["core", "graph", "sandbox"], true)),
        ("app without script", caps(&["core", "graph"], false)),
        ("playback-only runtime", caps(&["core"], false)),
    ];
    let picks: Vec<Value> = profiles
        .iter()
        .map(|(name, c)| match m.select(c) {
            Ok(v) => json!({ "runtime": name, "plays": format!("{:?}", v.tier) }),
            Err(e) => json!({ "runtime": name, "error": e.to_string() }),
        })
        .collect();
    Ok(json!({ "id": m.id, "revision": m.revision, "title": m.title, "signed": m.signature.is_some(), "variants": variants, "picks": picks, "fonts": m.fonts }))
}

pub fn bundle_text(v: &Value) -> String {
    let mut s = format!("{} (revision {}){}\n", v["id"].as_str().unwrap_or(""), v["revision"].as_str().unwrap_or(""), if v["signed"] == true { ", signed" } else { "" });
    for var in v["variants"].as_array().into_iter().flatten() {
        s += &format!("  {}  {:>8} bytes  {:>7} gzipped  [{}]\n", var["tier"].as_str().unwrap_or(""), var["bytes"], var["gzip"], var["chunks"].as_array().into_iter().flatten().filter_map(|c| c.as_str()).collect::<Vec<_>>().join(", "));
    }
    let fonts = v["fonts"].as_array().cloned().unwrap_or_default();
    if !fonts.is_empty() {
        s += "fonts:\n";
        for f in &fonts {
            s += &format!("  {} {}{}  {}  from {}\n", f["family"].as_str().unwrap_or(""), f["weight"], if f["italic"] == true { " italic" } else { "" }, f["licence"].as_str().unwrap_or(""), f["from"].as_str().unwrap_or(""));
        }
    }
    s += "picks:\n";
    for p in v["picks"].as_array().into_iter().flatten() {
        s += &format!("  {:<44} {}\n", p["runtime"].as_str().unwrap_or(""), p["plays"].as_str().or(p["error"].as_str()).unwrap_or(""));
    }
    s
}

/// `datars fonts`: every font token — what it names, where its face comes from, the face the
/// engine draws with, whether that is the token's own family, and its licence.
pub fn fonts_report(engine: &datars_engine::Engine) -> Vec<serde_json::Value> {
    let db = engine.fonts();
    let infos = db.faces();
    engine
        .theme()
        .fonts
        .iter()
        .map(|(token, spec)| {
            let face = db.face_id(&spec.stack().join(", "), spec.weight, spec.italic);
            let info = face.as_ref().and_then(|id| infos.iter().find(|f| &f.id == id));
            let loaded = spec.primary().is_some_and(|fam| info.is_some_and(|i| i.family.eq_ignore_ascii_case(&fam)));
            let licence = face.as_ref().and_then(|id| db.face_data(id)).map(|(b, i)| datars_build::fonts::licence(b, i).id);
            serde_json::json!({
                "token": token, "family": spec.stack(), "weight": spec.weight, "italic": spec.italic,
                "source": spec.source_url(), "face": face, "loaded": loaded,
                "licence": licence, "fs_type": info.map(|i| i.fs_type),
            })
        })
        .collect()
}

/// Loads a document with its files from a directory (the CLI's `load`).
pub type LoadFn = dyn Fn(&str, Option<&std::path::Path>) -> Result<datars_engine::Engine, String>;

/// `datars profile`, for explorable views: what a reader's pans and zooms cost per frame, from the
/// first frame of a freshly loaded document (indexing point pyramids included) to zooms and pans at
/// several depths — engine frame time (fill, display list, hash; no rasterizing: that's the
/// host's GPU) and what it drew. Nothing is printed for documents without an explorable view.
pub fn profile_explore(source: &str, dir: &std::path::Path, engine: &mut datars_engine::Engine, load: &LoadFn) -> Result<(), String> {
    use datars_engine::Pointer;
    let vp = engine.viewport();
    let (cx, cy) = (vp.width / 2.0, vp.height / 2.0);
    engine.goto(0);
    engine.frame(1000.0);
    if !engine.wheel(datars_math::Vec2::new(cx, cy), 0.0) {
        return Ok(());
    }
    // A fresh engine: the first frame pays for indexing.
    let mut fresh = load(source, Some(dir))?;
    let t = std::time::Instant::now();
    fresh.frame(0.0);
    let first = t.elapsed().as_secs_f64() * 1000.0;
    let ps = fresh.point_stats();
    if ps.rows > 0 {
        println!("explore: first frame {first:.0} ms ({} rows indexed into point pyramids)", fmt_int(ps.rows));
    } else {
        println!("explore: first frame {first:.1} ms");
    }
    let mut now = 1000.0;
    let frame = |e: &mut datars_engine::Engine, now: &mut f64| -> f64 {
        *now += 1.0;
        let t = std::time::Instant::now();
        let f = e.frame(*now);
        std::hint::black_box(f.hash());
        t.elapsed().as_secs_f64() * 1000.0
    };
    let median = |mut v: Vec<f64>| {
        v.sort_by(|a, b| a.total_cmp(b));
        v[v.len() / 2]
    };
    let report = |e: &datars_engine::Engine, what: &str, ms: f64| {
        let s = e.point_stats();
        let drawn = if s.rows > 0 { format!("   {} of {} points drawn (level {}, {} tiles)", fmt_int(s.drawn), fmt_int(s.rows), s.level, s.tiles) } else { String::new() };
        println!("  {what:<24} frame {ms:>7.2} ms{drawn}");
    };
    // Zoom in about the centre, ×2 at a time; at each depth, a pan (drag) measured over a few frames.
    frame(engine, &mut now);
    let whole: Vec<f64> = (0..5).map(|_| frame(engine, &mut now)).collect();
    report(engine, "whole", median(whole));
    for step in 1..=10 {
        engine.set_clock(now);
        engine.pointer(Pointer::Wheel { x: cx, y: cy, delta: -462.0 });
        let zoom_ms = frame(engine, &mut now);
        let mut pans = Vec::new();
        for k in 0..6 {
            let dx = if k % 2 == 0 { 40.0 } else { -40.0 };
            engine.pointer(Pointer::Down { x: cx, y: cy });
            engine.pointer(Pointer::Move { x: cx + dx, y: cy });
            engine.pointer(Pointer::Up { x: cx + dx, y: cy });
            pans.push(frame(engine, &mut now));
        }
        report(engine, &format!("zoom ×{} (step)", 1u64 << step), zoom_ms);
        report(engine, &format!("zoom ×{} (pan)", 1u64 << step), median(pans));
    }
    Ok(())
}

fn fmt_int(n: u64) -> String {
    let s = n.to_string();
    let mut out = String::new();
    for (i, c) in s.chars().enumerate() {
        if i > 0 && (s.len() - i).is_multiple_of(3) {
            out.push(',');
        }
        out.push(c);
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_fonts_report_names_sources_faces_and_licences() {
        let dir = std::path::Path::new(concat!(env!("CARGO_MANIFEST_DIR"), "/../../examples/serif"));
        let json = std::fs::read_to_string(dir.join("doc.json")).unwrap();
        let mut json_doc: serde_json::Value = serde_json::from_str(&json).unwrap();
        json_doc["theme"]["themes"][0]["tokens"]["font.strong"] = serde_json::json!({ "family": "GT America", "weight": 600 });
        let e = datars_headless::load_at(&json_doc.to_string(), Some(dir)).unwrap();
        let rows = fonts_report(&e);
        let row = |t: &str| rows.iter().find(|r| r["token"] == t).unwrap().clone();
        assert_eq!(row("font.title")["face"], "Newsreader-600");
        assert_eq!(row("font.title")["loaded"], true);
        assert_eq!(row("font.title")["licence"], "OFL-1.1");
        assert_eq!(row("font.title")["source"], "../../assets/fonts/Newsreader-SemiBold.ttf");
        assert_eq!(row("font.strong")["loaded"], false, "GT America has no face: drawn in a fallback");
        assert_eq!(row("font.strong")["source"], serde_json::Value::Null);
    }

    #[test]
    fn scenes_diff_by_key_path() {
        let doc = |v: [i32; 3]| {
            serde_json::json!({ "datars": 1, "size": { "width": 100, "height": 50 },
                "data": { "t": { "values": { "k": ["a", "b", "c"], "v": v }, "key": ["k"] } },
                "tables": { "shown": { "from": "t", "ops": [{ "op": "filter", "expr": "=d.v > 0" }] } },
                "scene": { "kind": "repeat", "from": "shown", "template": { "kind": "shape", "geom": { "type": "rect", "x": "=d.v * 10", "y": 0, "w": 5, "h": 5 }, "fill": "$accent" } } })
            .to_string()
        };
        let scene = |j: String| {
            let mut e = datars_engine::Engine::new();
            e.load(datars_ir::Doc::from_json(&j).unwrap());
            e.scene()
        };
        let d = diff(&scene(doc([1, 2, 0])), &scene(doc([1, 3, 4])));
        assert_eq!(d["added"].as_array().unwrap().len(), 1, "{d}");
        assert!(d["added"][0]["path"].as_str().unwrap().ends_with("(\"c\",)"));
        assert_eq!(d["changed"].as_array().unwrap().len(), 1, "b moved");
        assert!(d["removed"].as_array().unwrap().is_empty());
        assert!(diff_text(&d).contains("1 added, 0 removed, 1 changed"));
    }

    #[test]
    fn migrate_reports_changes_and_ignored_fields() {
        let (v, notes, ignored) = migrate(r##"{"datars":1,"size":{"width":10,"height":10},"scene":{"kind":"view","clip":true,"children":[],"fil":"#000"}}"##).unwrap();
        assert!(v["scene"].get("clip").is_none());
        assert_eq!(notes.len(), 1);
        assert_eq!(ignored, vec!["scene.fil".to_string()]);
    }

    #[test]
    fn a_bundle_says_what_each_runtime_plays() {
        let doc = r#"{"datars":1,"size":{"width":100,"height":50},"scene":{"kind":"shape","key":"b","geom":{"type":"rect","x":0,"y":0,"w":10,"h":10},"fill":"$accent"}}"#;
        let (b, _) = datars_build::build(doc, &datars_build::Options::default()).unwrap();
        let v = bundle_inspect(&datars_bundle::to_single_file(&b)).unwrap();
        let picks = v["picks"].as_array().unwrap();
        assert_eq!(picks[0]["plays"], "T2", "{v}");
        assert_eq!(picks[1]["plays"], "T3");
        assert_eq!(picks[4]["plays"], "T1");
        assert!(bundle_text(&v).contains("picks:"));
    }

    /// The committed reference and llms.txt are what `datars docs` generates now.
    #[test]
    fn generated_docs_are_current() {
        let root = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../..");
        let all = datars_devtools::describe_std(&datars_engine::Engine::new());
        assert!(all.len() > 30);
        let reference = reference_md(&all);
        let llms = llms_txt(&all, crate::HELP);
        assert!(reference.contains("## bar") && reference.contains("| `labels` | bool |"));
        assert!(llms.contains("`std/pareto`") && llms.contains("datars new"));
        let stale = |f: &str, want: &str| std::fs::read_to_string(root.join(f)).ok().as_deref() != Some(want);
        assert!(!stale("docs/reference/std.md", &reference) && !stale("llms.txt", &llms) && !stale("docs/reference/ir.schema.json", &schema_json()), "generated docs are stale: run `datars docs`");
    }
}
